import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { random as random2 } from "lodash"


import { RamdomFox } from "../components/RamdomFox"


const random = (): number => random2(1, 123)

const generadeId = (): string => {
  return Math.random().toString(36).substr(2, 9);
}

const image =  (): string =>  { 
  return `https://randomfox.ca/images/${random()}.jpg`
}

const imagesItems = () => {
   const items: IFoxImageItems = { id: generadeId() ,url: image() }
   return items
}

const Home: NextPage = () => {

  const [images, setImages] = useState<IFoxImageItems[]>([]);
 
  const addNewFox = () => {

    setImages([
      ...images,
      imagesItems()
    ])

    window.plausible('add_fox')
  }

  return (
    <div>
      <Head>
        <title>Random Fox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script defer data-domain="yourdomain.com" src="https://plausible.io/js/script.js"></script>
      </Head>

      <main>
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 className="text-2xl font-bold tracking-tight text-gray-900">Random Fox</h2>
            <button onClick={addNewFox} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">add new fox</button>
            <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {images.map((imagess, index) => (
              <div className="group relative">  
                <div key={imagess.id} className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
                  <RamdomFox 
                    src={imagess.url} 
                    title={`Fox number ${index + 1}`} 
                    onClick={() => console.log("hey you!")} 
                    onLazyLoad={((img) => {console.log(`Image #${index + 1} cargada. Nodo:`, img)})}
                  />
                </div>
              </div>  
              ))
              }  
            </div>  
          </div>
      </main>

      <footer>
      </footer>
    </div>
  );
};

export default Home;